
@localhost = localhost
@prodhost = cse341-lesson1.onrender.com


// LOCALHOST

### Get All Contacts
GET http://{{localhost}}:3000/contacts

### Get Single Contact
GET http://{{localhost}}:3000/contacts/?id=6337b5f65b300b15049eb1bb

### Create Contact 
POST http://{{localhost}}:3000/contacts/ HTTP/1.1 
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john@contacts.com",
    "favoriteColor": "blue",
    "birthday": "10/20/1995",
}

### Update Contact
PUT http://{{localhost}}:3000/contacts/6337b5f65b300b15049eb1bb HTTP/1.1 
content-type: application/json

{
    "firstName": "Mark",
    "lastName": "Gates",
    "email": "mark@contacts.com",
    "favoriteColor": "red",
    "birthday": "11/23/1956",
}

### Delete Contact
DELETE http://{{localhost}}:3000/contacts/6337b5f65b300b15049eb1bb

// PRODUCTION

### Get All Contacts
GET http://{{prodhost}}/contacts

### Get Single Contact
GET http://{{prodhost}}/contacts/?id=6337b63c88261cb660ae4314

### Create Contact 
POST http://{{prodhost}}/contacts/ HTTP/1.1 
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john@contacts.com",
    "favoriteColor": "blue",
    "birthday": "10/20/1995",
}

### Update Contact
PUT http://{{prodhost}}/contacts/6337b63c88261cb660ae4314 HTTP/1.1 
content-type: application/json

{
    "firstName": "Mark",
    "lastName": "Gates",
    "email": "mark@contacts.com",
    "favoriteColor": "red",
    "birthday": "11/23/1956",
}

### Delete Contact
DELETE http://{{prodhost}}/contacts/6337b63c88261cb660ae4314